# Generated by Django 3.2.12 on 2025-05-23 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('cam_app2', '0004_videopage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoPage',
        ),
    ]
